### ISSUE TITLE
Add warning about perfect forward secrey

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-ohai/draft-ohai-chunked-ohttp#23]
Chunked OHTTP doesn't have perfect forward secrecy. In most scenarios, HTTPS is a better fit, with TLS 0-RTT to improve latency. HTTPS-over-CONNECT-over-HTTPS with TLS 0-RTT is a better fit for most applications that want the privacy guarantees of such a system, with one exception: when separate requests need to be uncorrelatable. That's because TLS 0-RTT uses TLS session tickets which allow linkability. I think we should add some text to security considerations here to make the tradeoffs clear. We don't want someone to accidentally lose perfect forward secrecy.

**Comment by martinthomson** [comment]
This is a property that is shared with the base OHTTP.  How important do you think that this is?  We already more or less include all the security considerations from the base protocol by reference.  Does this need a special callout?

**Comment by DavidSchinazi** [comment]
The original version of OHTTP was limited in terms of response sizes, which inherently limited the use cases that could work with it. Prior to this draft, the decision tree was:
* small transaction -> OHTTP
* long-lived exchange -> HTTPS-over-CONNECT

This specific draft changes this decision flow chart for long-lived exchanges, so we now need to explain when to pick one over the other.
